#!/bin/bash

#Beaker
#beakerx install
#jupyter labextension install beakerx-jupyterlab --dev

jupyter labextension install @jupyter-widgets/jupyterlab-manager --dev

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

jupyter labextension install @jupyterlab/github

jupyter labextension install jupyterlab-drawio

# Rise for Notebook (presentation mode)
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable  rise --py --sys-prefix
jupyter labextension install jupyterlab_rise

# Plotly For JupyterLab
jupyter labextension install @jupyterlab/plotly-extension

jupyter lab build

rm conda-bld -R