#!/bin/bash

#beakerx install
#jupyter labextension install beakerx-jupyterlab --dev

jupyter labextension install @jupyter-widgets/jupyterlab-manager --dev
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
jupyter labextension install @jupyterlab/github

jupyter lab build

rm conda-bld -R